#!/usr/bin/env python
"""
gen_html_header.py — Convert dashboard.html → dashboard_html.h

Reads the HTML source, escapes it as a C string literal, and wraps
it in a `const char *const DASHBOARD_HTML` declaration.

Usage:
  python tools/gen_html_header.py src/web/dashboard.html src/web/dashboard_html.h
"""
import sys, os

def escape_c_string(text):
    """Escape text for embedding as a C string literal."""
    out = []
    for ch in text:
        if ch == '\\': out.append('\\\\')
        elif ch == '"':  out.append('\\"')
        elif ch == '\n': out.append('\\n"\n"')
        elif ch == '\r': pass  # skip CR (Windows CRLF → just LF)
        elif ch == '\t': out.append('\\t')
        elif ord(ch) < 32: out.append(f'\\x{ord(ch):02x}')
        else: out.append(ch)
    return ''.join(out)

def main():
    html_path = sys.argv[1] if len(sys.argv) > 1 else 'src/web/dashboard.html'
    hdr_path  = sys.argv[2] if len(sys.argv) > 2 else 'src/web/dashboard_html.h'

    with open(html_path, 'r', encoding='utf-8') as f:
        html = f.read()

    # Escape for C string
    escaped = escape_c_string(html)

    # Generate header
    header = (
        '/**\n'
        ' * dashboard_html.h — Embedded dashboard SPA (auto-generated)\n'
        ' *\n'
        ' * DO NOT EDIT THIS FILE DIRECTLY.\n'
        ' * Generated from dashboard.html via:\n'
        f' *   python tools/gen_html_header.py {html_path} {hdr_path}\n'
        ' */\n'
        '\n'
        'const char *const DASHBOARD_HTML =\n'
        f'"{escaped}";\n'
    )

    with open(hdr_path, 'w', encoding='utf-8') as f:
        f.write(header)

    print(f'Generated {hdr_path} ({len(html)} chars HTML → {len(escaped)} chars C string)')

if __name__ == '__main__':
    main()
